
server:
  port: 8987
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB
  mvc:
    dispatch-options-request: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml